# Generated by Django 5.0.4 on 2024-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_age_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
