# Generated by Django 5.0.4 on 2024-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
