# Generated by Django 5.0.4 on 2024-06-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
    ]
